### ISSUE TITLE
Can't use an array as a reference at ..../cadubi line 341

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [statico/cadubi#2]
Hi! I'm trying to update FreeBSD port of cadubi from 1.3.0 to 1.3.1. With perl-5.22.1 I get the following error:

```
% cadubi
Can't use an array as a reference at /opt/bin/cadubi line 341.
```

Please, advise. Thank you!

**Comment by jibsheet** [comment]
Can you confirm https://github.com/statico/cadubi/pull/3 resolves this?

**Comment by matteocng** [comment]
#3 solves this on OS X El Capitan, perl 5, version 18, subversion 2 (v5.18.2).

**Comment by phls** [comment]
Hi Ian. Can you release a new version with this fix (1.3.2)? I would like to update the debian package with this new relaese.

**Comment by statico** [comment]
Sure thing!

**Comment by statico** [comment]
...and done: https://github.com/statico/cadubi/releases/tag/v1.3.2
